/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.PatientController;
import model.Patient;

/**
 *
 * @author piyus
 */
public class SearchPatientFrame extends javax.swing.JFrame {

    /**
     * Creates new form SearchPatientFrame
     */
    private MainFrame mainFrame;
    private int currentPatientId = -1;
   public SearchPatientFrame(MainFrame mainFrame) {
     this.mainFrame = mainFrame;
    initComponents();
    pack();
    setTitle("Search / Manage Patient");
    setLocationRelativeTo(null);
    setResizable(false);   // 🔒 FIXED SIZE
    setFormEnabled(false);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSearchTitle = new javax.swing.JLabel();
        lblSearchBy = new javax.swing.JLabel();
        cmbSearchType = new javax.swing.JComboBox<>();
        txtSearchValue = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtNotes = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtTreatment = new javax.swing.JTextArea();
        lblName1 = new javax.swing.JLabel();
        lblTreatment = new javax.swing.JLabel();
        lblMobile = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblNotes = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtMobile = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblSearchTitle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSearchTitle.setText("Search Patient ");

        lblSearchBy.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSearchBy.setText("Search By ");

        cmbSearchType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Patient ID", "Name", "Mobile" }));
        cmbSearchType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSearchTypeActionPerformed(evt);
            }
        });

        txtSearchValue.setToolTipText("Enter Patient Detail\n");

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        txtNotes.setColumns(20);
        txtNotes.setRows(5);
        jScrollPane1.setViewportView(txtNotes);

        txtTreatment.setColumns(20);
        txtTreatment.setRows(5);
        jScrollPane2.setViewportView(txtTreatment);

        lblName1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblName1.setText("Patient Name");

        lblTreatment.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTreatment.setText("Treatment");

        lblMobile.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMobile.setText("Mobile Number");

        lblDate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDate.setText("Date (YYYY-MM-DD)");

        lblNotes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNotes.setText("Diseases/Notes");

        txtDate.setToolTipText("Date");

        txtName.setToolTipText("Name");
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        txtMobile.setToolTipText("Mobile\n");
        txtMobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMobileActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnBack.setText("Back to Main Page ");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblName1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNotes, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblMobile, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtDate)
                                        .addComponent(txtMobile)
                                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTreatment, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(146, 146, 146)
                                .addComponent(lblSearchTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblSearchBy))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(cmbSearchType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtSearchValue, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSearch)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(17, 17, 17))
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(btnUpdate)
                .addGap(18, 18, 18)
                .addComponent(btnDelete)
                .addGap(28, 28, 28)
                .addComponent(btnClear)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblSearchTitle)
                .addGap(7, 7, 7)
                .addComponent(btnBack)
                .addGap(4, 4, 4)
                .addComponent(lblSearchBy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbSearchType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearchValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName1)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMobile)
                    .addComponent(txtMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDate)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lblNotes))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnUpdate)
                                    .addComponent(btnDelete)
                                    .addComponent(btnClear)))
                            .addComponent(lblTreatment))))
                .addContainerGap(110, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbSearchTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSearchTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSearchTypeActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtMobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMobileActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
       
        String searchValue = txtSearchValue.getText().trim();
    if (searchValue.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Please enter search value");
        return;
    }

    String searchType = cmbSearchType.getSelectedItem().toString();
    Patient patient = null;

    PatientController controller = new PatientController();

    if (searchType.equals("Patient ID")) {

        int patientId;
        try {
            patientId = Integer.parseInt(searchValue);
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Patient ID must be a number");
            return;
        }

        patient = controller.getPatientById(patientId);

    } else if (searchType.equals("Name")) {

        patient = controller.getPatientByName(searchValue);
    }
    else if (searchType.equals("Mobile")) {

    patient = controller.getPatientByMobile(searchValue);
}


   if (patient == null) {
    javax.swing.JOptionPane.showMessageDialog(this,
        "Patient not found");
    setFormEnabled(false);   // 🔒 lock form
    currentPatientId = -1;
    return;
}
currentPatientId = patient.getPatientId();
    txtName.setText(patient.getName());
    txtMobile.setText(patient.getMobile());
    txtDate.setText(patient.getVisitDate().toString());
    txtTreatment.setText(patient.getTreatment());
    txtNotes.setText(patient.getNotes());
    setFormEnabled(true); // ✅ allow edit now
    
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        if (currentPatientId == -1) {
    javax.swing.JOptionPane.showMessageDialog(this,
        "Please search a patient first");
    return;
}

String name = txtName.getText().trim();
String mobile = txtMobile.getText().trim();
if (!mobile.matches("\\d{10}")) {
    javax.swing.JOptionPane.showMessageDialog(this,
        "Mobile number must be exactly 10 digits");
    return;
}
String dateStr = txtDate.getText().trim();
String treatment = txtTreatment.getText().trim();
String notes = txtNotes.getText().trim();


if (name.isEmpty() || mobile.isEmpty() || dateStr.isEmpty() || treatment.isEmpty()) {
    javax.swing.JOptionPane.showMessageDialog(this,
        "All required fields must be filled");
    return;
}

java.util.Date visitDate;
try {
    visitDate = java.sql.Date.valueOf(dateStr);
} catch (Exception e) {
    javax.swing.JOptionPane.showMessageDialog(this,
        "Invalid date format (YYYY-MM-DD)");
    return;
}

Patient patient = new Patient(
    currentPatientId,
    name,
    mobile,
    visitDate,
    treatment,
    notes
);

boolean updated = new PatientController().updatePatient(patient);

if (updated) {
    javax.swing.JOptionPane.showMessageDialog(this,
        "Patient record updated successfully");
}

else {
    javax.swing.JOptionPane.showMessageDialog(this,
        "Update failed");
}
mainFrame.loadPatientsTable(); // 🔄 refresh dashboard
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        if (currentPatientId == -1) {
    javax.swing.JOptionPane.showMessageDialog(this,
        "Please search a patient first");
    return;
}

// Confirmation dialog
int confirm = javax.swing.JOptionPane.showConfirmDialog(
        this,
        "Are you sure you want to delete this patient?",
        "Confirm Delete",
        javax.swing.JOptionPane.YES_NO_OPTION
);

if (confirm != javax.swing.JOptionPane.YES_OPTION) {
    return;
}

boolean deleted = new PatientController().deletePatient(currentPatientId);

if (deleted) {
    javax.swing.JOptionPane.showMessageDialog(this,
        "Patient deleted successfully");

    // Clear fields
    txtName.setText("");
    txtMobile.setText("");
    txtDate.setText("");
    txtTreatment.setText("");
    txtNotes.setText("");

    currentPatientId = -1; // reset
    setFormEnabled(false);
} else {
    javax.swing.JOptionPane.showMessageDialog(this,
        "Delete failed");
}
mainFrame.loadPatientsTable(); // 🔄 refresh dashboard
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txtSearchValue.setText("");
cmbSearchType.setSelectedIndex(0);

txtName.setText("");
txtMobile.setText("");
txtDate.setText("");
txtTreatment.setText("");
txtNotes.setText("");

currentPatientId = -1;
setFormEnabled(false);

    }//GEN-LAST:event_btnClearActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        new view.MainFrame().setVisible(true);
this.dispose(); // close SearchPatientFrame
    }//GEN-LAST:event_btnBackActionPerformed

    private void setFormEnabled(boolean enabled) {
    txtName.setEnabled(enabled);
    txtMobile.setEnabled(enabled);
    txtDate.setEnabled(enabled);
    txtTreatment.setEnabled(enabled);
    txtNotes.setEnabled(enabled);

    btnUpdate.setEnabled(enabled);
    btnDelete.setEnabled(enabled);
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchPatientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchPatientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchPatientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchPatientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       // java.awt.EventQueue.invokeLater(new Runnable() {
        //    public void run() {
         //       new SearchPatientFrame().setVisible(true);
         //   }
        //});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbSearchType;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblMobile;
    private javax.swing.JLabel lblName1;
    private javax.swing.JLabel lblNotes;
    private javax.swing.JLabel lblSearchBy;
    private javax.swing.JLabel lblSearchTitle;
    private javax.swing.JLabel lblTreatment;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtMobile;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextArea txtNotes;
    private javax.swing.JTextField txtSearchValue;
    private javax.swing.JTextArea txtTreatment;
    // End of variables declaration//GEN-END:variables
}
